### ISSUE TITLE
Template rendering is insanely slow when using this package   

### ISSUE THREAD

**Issue by ClimenteA** [christianwgd/django-bootstrap-icons#32]
Hi,

Not sure what happens, but I have a table with 100 rows in which I render some icons and it takes 20 seconds to finish. I took me a while to figure out what caused that slowdown :sweat_smile: .

**Comment by christianwgd** [comment]
Did you enable the icon cache like described in the doc [here](https://github.com/christianwgd/django-bootstrap-icons#configure-icon-cache)? This should prevent these extended loading times.

**Comment by christianwgd** [comment]
Just tested this by myself and added four different icons one hundert times in a table. With icon cache enabled I had no findings on unusual response times. 

You can find this sample code in the test app in the "samples" template.

**Comment by ClimenteA** [comment]
Missed that. I didn't add the cache dir.

Thank you for your response!
