### ISSUE TITLE
Multiple instances of icons causes site to exponentially slow down

### ISSUE THREAD

**Issue by supun-kalhara** [christianwgd/django-bootstrap-icons#7]
As I loaded more icons in my template file on my django project, the site slowed down considerable. Even when I included just 5 icons there was a noticeable difference in site load times. I'm not sure why this is currently but it's a huge downside to using icons in django templates this way.

**Comment by christianwgd** [comment]
This is why i introduced the icon cache in release 0.6.2 (issue #5, https://github.com/christianwgd/django-bootstrap-icons#configure-icon-cache). Did you try that? If that doesn't help, let me know, then we may have another problem.

**Comment by supun-kalhara** [comment]
Yes this worked; I'm somewhat new to django so I didn't fully understand your documentation, thank you so much.
